# Site settings
author: Yazgylych Rahymov
title: Create CLI Gem 
header-img: img/home-bg.png
email: y.rahymov@gmail.com
copyright_name: Yazgylych Rahymov
description: > # this means to ignore newlines until "baseurl:"
  How to create CLI gem
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rahymov

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
